### ISSUE TITLE
Issue with UseAnsi

### ISSUE THREAD

**Issue by ryno1234** [cschlote/MediaInfoDotNet#12]
I am looking to add Linux compatibility for this library. I've forked it and working on an update. There are alternatives around but I like the way this library works.

That said, I did notice that after my initial adjustments, the library didn't work as intended on Linux in the most basic operations. I tracked this down to the value of `UseAnsi`. When comparing this to the alternative library (see https://github.com/StefH/MediaInfo.DotNetWrapper/blob/1c89fe6fe12f997800cdcc79e792ad56c2450f68/src/MediaInfo.DotNetWrapper/MediaInfo.cs#L25 ), it appears this library is using exact oposite logic for determining if we should be using Ansi or not.

When flipping the logic, this library works on both Windows and Linux. Ex:

	if (Environment.OSVersion.ToString().IndexOf("Windows") == -1)
	{
		MustUseAnsi = true;
	}
	else
	{
		// Determine bitness of system and pre-load appropriate library
		if (moduleHandle == IntPtr.Zero)
		{
			string fullexepath = new Uri(Assembly.GetExecutingAssembly().CodeBase).AbsolutePath;
			if (fullexepath != String.Empty)
			{
				FileInfo fi = new FileInfo(fullexepath);
				fullexepath = Uri.UnescapeDataString(Path.Combine(fi.Directory.FullName, Environment.Is64BitProcess ? "x64" : "x86", "mediainfo"));
				moduleHandle = UnsafeNativeMethods.LoadLibraryEx(fullexepath, IntPtr.Zero, 0);
			}
			else
			{
				Trace.TraceWarning("MediaInfoDotNet could not automatically load MediaInfo.dll. You will need to manually load the file using using LoadLibraryEx() or ensuring that the file is in the default library search paths.");
			}
		}

		MustUseAnsi = false;
	}

**Comment by cschlote** [comment]
Since I moved to Linux completely as platform, I'm a bit handicaped to work with C# ;-) When I find some time to update my Windows and VisualStudio and ... I will come back for these issues.

**Comment by ryno1234** [comment]
Are you accepting Pull requests? We are adding this library to our project and will be using it on Linux. If we get it working, are you open to merging the changes into your line of code?

**Comment by ryno1234** [comment]
I've confirmed that this logic that I'm suggesting also aligns with https://github.com/MediaArea/MediaInfoLib/blob/5ddd15004c2cf9efce77c772402cc591c652ff77/Source/MediaInfoDLL/MediaInfoDLL.cs#L133.

Once I have everything buttoned up, I'll submit a PR.

**Comment by ryno1234** [comment]
This issue has been fixed in Pull Request https://github.com/cschlote/MediaInfoDotNet/pull/13
